### ISSUE TITLE
CI test fails even if pre-built...

### ISSUE THREAD

**Issue by AubreyHewes** [kingsquare/communibase-connector-js#8]
It seems that the CI is not using the post-build lib to run tests..

    SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by fruitl00p** [comment]
seems about right... but we could also create a new 3.0.0 release and target node 6+ (or even 8+) and leave the babel for what it is...?

**Comment by AubreyHewes** [comment]
The root problem is `The tests are run on the pre-babel code`. We want the code to have "old" support.. but we are testing on "new" code

**Comment by AubreyHewes** [comment]
Currently the tests are run by the engine version.
Maybe update to a node-latest build container ... with `n` ...

 * babel the code
 * test the code
 * n to min-req version
 * test the code

?

**Comment by Reggino** [comment]
Dit is gefixt
